### PR TITLE
fix build script after rename and split into 3 projects

### LINKED ISSUE #4: Build script needs to be fixed / updated
The build script is not working due to the solution being renamed. It looks like VB is also missing from the build.

### PR DESCRIPTION
**Pull request by adamralph**
fixes #4

### CODE REVIEW

**Comment by filipw** [comment]
thanks

**Comment by filipw** [comment]
though I am not 100% convinced if there's value in packaging the common assembly as nuget too or whether we just go with the 2 language specific engines

**Comment by adamralph** [comment]
Yeah, we could just link the files into both projects.

**Comment by adamralph** [comment]
I've set up a build at codebetter CI - http://teamcity.codebetter.com/viewType.html?buildTypeId=Scriptcs_ScriptCsEngines

At the moment, I can't add GitHub status reporting, or enable a TravisCI build, since the core team are not permissioned on this repo.

The submodule caused some problems, which I managed to workaround, but I think you can remove this now and just use the NuGet packages. We just need https://github.com/scriptcs/scriptcs/pull/969 to be merged to remove the breaking changes currently in the dev branch.

**Pull request merged**
